version: 2
updates:
  - package-ecosystem: maven
    directory: '/'
    ignore:
      - dependency-name: 'com.icegreen:greenmail-junit5'
        update-types: [ 'version-update:semver-major' ]
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 100
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 100
