name: Build


on:
  push:
    branches:
      # Run for all branches (except for Release Please branches)
      # This implies not running for tags
      - '**'
      - '!release-please--*'
    paths:
      - '.github/workflows/build.yaml'
      - '**/src/**'
      - '**/pom.xml'
      - 'checkstyle-suppressions.xml'
      - '!**/*.md'
      - '!.github/CODEOWNERS'
      - '!.github/dependabot.yaml'
      - '!.github/**/*release-please*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK/Maven
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
      - name: Build and verify all modules
        run: >-
          mvn
          --batch-mode
          --activate-profiles=checkstyle,spotbugs,coverage
          "-DrepoBaseUrl=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
          verify
