name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version number'
        required: true
      developmentVersion:
        description: 'Next development (snapshot) version number'
        required: true

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Check out from SCM
        uses: actions/checkout@v2
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Set up JDK/Maven
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Configure Maven settings
        uses: whelk-io/maven-settings-xml-action@v10
        with:
          servers: >-
            [{
              "id": "ossrh",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.OSS_PASSWORD }}"
            }]
      - name: Configure git
        run: |
          git config --global committer.email "noreply@github.com"
          git config --global committer.name "GitHub Actions"
          git config --global author.email "${{ github.actor }}@users.noreply.github.com"
          git config --global author.name "${{ github.actor }}"
      - name: Prepare release
        id: prepare_release
        run: >-
          mvn
          --batch-mode
          --file parent-pom.xml
          release:prepare
          -DpomFileName=parent-pom.xml
          "-DpreparationGoals=clean compile"
          "-DreleaseVersion=${{ github.event.inputs.releaseVersion }}"
          "-DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}"
          "-Dtag=v${{ github.event.inputs.releaseVersion }}"
          "-Dusername=${{ github.actor }}"
          "-Dpassword=${{ secrets.GITHUB_TOKEN }}"
      # Intentionally using pom.xml - not parent-pom.xml.
      # We do want to release only one single self-contained artifact with no reference to a parent project.
      # The purpose of parent-pom.xml is having an entry point for preparing (and rolling back) a release
      # with the help of the Maven Release Plugin.
      - name: Perform release
        id: perform_release
        run: >-
          mvn
          --batch-mode
          --file pom.xml
          release:perform
          -DpomFileName=pom.xml
          -Dgoals=deploy
          -DreleaseProfiles=release
          "-Darguments=-Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}"
          "-Dusername=${{ github.actor }}"
          "-Dpassword=${{ secrets.GITHUB_TOKEN }}"
      # Maven Release Plugin 3.0.0-M1 would automatically remove the tag but unfortunately
      # it's unusable due to this bug: https://issues.apache.org/jira/browse/MRELEASE-1038
      # Hence, for the time being, we have to delete the tag ourselves.
      - name: 'In case of failure: Rollback'
        id: rollback
        if: failure()
        run: >-
          git tag -d "v${{ github.event.inputs.releaseVersion }}" && git push origin ":refs/tags/v${{ github.event.inputs.releaseVersion }}"
          ;
          mvn
          --batch-mode
          --file parent-pom.xml
          release:rollback
          -DpomFileName=parent-pom.xml
          "-Dusername=${{ github.actor }}"
          "-Dpassword=${{ secrets.GITHUB_TOKEN }}"
      - name: Create GitHub release
        id: create_github_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.releaseVersion }}
          release_name: hamcrest-mail-${{ github.event.inputs.releaseVersion }}
          body: |-
            Release ${{ github.event.inputs.releaseVersion }} of hamcrest-mail
            
            [Change log](https://github.com/devopsix/hamcrest-mail/blob/master/CHANGES.md)
      - name: Upload release JAR file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_github_release.outputs.upload_url }} 
          asset_path: ./target/checkout/target/hamcrest-mail-${{ github.event.inputs.releaseVersion }}.jar
          asset_name: hamcrest-mail-${{ github.event.inputs.releaseVersion }}.jar
          asset_content_type: application/java-archive
      - name: Upload release javadoc JAR file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_github_release.outputs.upload_url }} 
          asset_path: ./target/checkout/target/hamcrest-mail-${{ github.event.inputs.releaseVersion }}-javadoc.jar
          asset_name: hamcrest-mail-${{ github.event.inputs.releaseVersion }}-javadoc.jar
          asset_content_type: application/java-archive
